version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    tty: true
    ports:
      - "3000:3000"
    networks:
      - node-network
networks:
  node-network:
    driver: bridge