version: '3.9'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    restart: always
    command: node dist/src/main
    volumes:
      - /usr/src/app
      - /usr/src/node_modules
    env_file:
      - ./app/.env
    tty: true
    networks:
      - show-sizzle
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - show-sizzle
    ports:
      - "5500:80"
    depends_on:
      - app
networks:
  show-sizzle:
    driver: bridge